site_name: AEGIS Documentation
site_url: http://aegis.stanford.edu
site_description: Project documentation for AEGIS
site_author: Junjie (Jason) Zhu

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

extra_css:
    - css/extra.css

nav:
    - Home: 'index.md'
    - User Guide:
        - 'Installation': 'install.md'
        - 'Video Tutorials': 'tutorial.md'
        - 'Web Interface Manual': 'manual.md'
        - 'API Documentation': 'api.md'
    - Jupyter Notebooks: # 'notebooks.md'
        - 'Single Cell RNA-seq Application': 'notebooks/aegis_single_cell_example.html'
        - 'Benchmark for Testing: Part 1': 'notebooks/aegis_benchmark_part1.html'
        - 'Benchmark for Testing: Part 2': 'notebooks/aegis_benchmark_part2.html'

