site_name: aegis documentation
nav:
- Home: 'index.md'
- Notebooks:
    - 'Single Cell RNA-seq Application' : 'notebooks/aegis_single_cell_example.html'
    - 'Benchmark for DAG-based Testing: Part I' : 'notebooks/aegis_benchmark_part1.html'
    - 'Benchmark for DAG-based Testing: Part II' : 'notebooks/aegis_benchmark_part2.html'
